name: my_workout
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  collection: ^1.18.0
  duration_picker: ^1.2.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_timer_countdown: ^1.0.7
  intl: ^0.19.0
  numberpicker: ^2.1.2
  path: ^1.9.0
  path_provider: ^2.1.4
  share_plus: ^10.1.0
  stop_watch_timer: ^3.2.1
  timelines_plus: ^1.0.6
  uuid: ^4.5.1
  vibration: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
